config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "pages#home"
  get "meetings/analytics", to: "meetings#analytics"
  resources :meetings do
    resources :bookings, only: [:edit, :update]
    resources :messages, only: :create
    resources :videos, only: :create
    get '/party', to: 'video#index'
    patch '/party', to: 'video#index'
    get '/screenshare', to: 'video#screenshare'
    post '/name', to: 'video#name'
  end
  resources :videos, only: :update
  resources :bookings, only: [:destroy]
  get "users/:id/card", to: "users#card", as: "user_card"
  get "meetings/:id/duration", to: "meetings#duration", as: "meeting_reason"
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :video, optional: true
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many :messages, dependent: :destroy

  validates :description, presence: true
  validates :duration, presence: true
  # validates :objectives, presence: true
  # validates :agenda, presence: true
  validates :location, presence: true
  validates :start_date, presence: true

  def sync_to_google_calendar(users_names)
    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = Google::Apis::RequestOptions.default.authorization

    meeting = Google::Apis::CalendarV3::Event.new(
      summary: title,
      description: description,
      start: {
        date_time: start_date.iso8601
      },
      end: {
        date_time: end_date.iso8601
      },
      location: location,
      attendees: build_attendees_list(users_names)
    )

        # Insert the event into Google Calendar
        calendar_id = 'primary' # Use 'primary' for the default calendar
        result = service.insert_event(calendar_id, meeting)

        # Handle the result
        if result.status == 'confirmed'
          # Event successfully added to Google Calendar
        else
          # Handle the error, e.g., log it or show an error message
        end
      end



      def build_attendees_list(users_names)
        attendees_list = []
        users_names.each do |name|
          user_instance = User.find_by(name: name)
          attendees_list << Google::Apis::CalendarV3::EventAttendee.new(email: user_instance.email) if user_instance.present?
        end
        attendees_list
      end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def index
    @user = User.find_by(id: params[:user_id]) || current_user
    if params[:query] && params[:query] != ""
      @users_filtered = User.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @users_filtered = []
    end
    respond_to do |format|
      format.html
      format.text{ render partial: "avatars", locals: { users: @users_filtered }, formats: [:html] }
    end
    @past_meetings = @user.meetings_as_owner.where("start_date < ?", DateTime.now).order(:start_date)
    @upcoming_meetings = @user.meetings_as_owner.where("start_date > ?", DateTime.now).order(:start_date)
    @users = User.where.not(id: current_user)
    @meetings = policy_scope(@user.meetings.where(
      start_date: (Time.now.beginning_of_month - 3.month).beginning_of_week..(Time.now.end_of_month + 1.month).end_of_week
    ))
  end

  def analytics
    @user = User.find_by(id: params[:user_id]) || current_user
    @users = User.all
    if params[:query] && params[:query] != ""
      @users_filtered = User.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @users_filtered = []
    end
    respond_to do |format|
      format.html
      format.text { render partial: "avatarsfa", locals: { users: @users_filtered }, formats: [:html] }
    end

    @meetings = Meeting.all
    @meetings_user = current_user.meetings
    @bookings = Booking.all
    @bookings_user = current_user.bookings
    authorize @meetings

    # total
    @date = Date.today
    @total_duration_a = 0
    @users.each { |user| user.meetings.each { |meeting| @total_duration_a += meeting.duration.to_i } }

    @allcount = 0
    @users.each { |user| @allcount += user.meetings.count }

    @all_average = @total_duration_a / @allcount

    user_total = {}
    @users.map { |user| user_total[user.name] = user.meetings.count }
    @top = user_total.max { |x, y| x[1] <=> y[1] }

    # calculate each month

    def weekday_hour(date)
      wd = 0
      (Date.new(date.year, date.month, 1)..Date.new(date.year, date.month, -1)).each { |day| wd += 1 if !(day.saturday? || day.sunday? ) }
      wd * 8
    end

    def total_duration(date)
      total_duration = 0
      @users.each do |user|
        user.meetings.where(start_date: date.beginning_of_month..date.end_of_month).each { |meeting| total_duration += meeting.duration.to_i}
      end
      total_duration
    end

    def total_count(date)
      count = 0
      @users.each { |user| count += user.meetings.where(start_date: date.beginning_of_month..date.end_of_month).count }
      count
    end

    def top(date)
      user_total = {}
     @users.map do |user|
        user_total[user.name] = user.meetings.where(start_date: date.beginning_of_month..date.end_of_month).count
      end
     user_total.max{ |x, y| x[1] <=> y[1] }
    end

    # def average(date)
    #   total_duration(date) / total_count(date)
    # end

    def average(date)
     count = total_count(date)
     if count > 0
      total_duration(date) / count
     else
       0  # or handle the case when count is zero appropriately
     end
    end

    # thismonth all
    @date = Date.today
    @this_total = total_duration(@date)
    @this_count = total_count(@date)
    @this_average = average(@date)
    @this_top = top(@date)

    # lastmonth all
    @last_date = Date.today.last_month
    @last_total = total_duration(@last_date)
    @last_count = total_count(@last_date)
    @last_average = average(@last_date)
    @last_top = top(@last_date)

    # each user
    def user_total(date)
      total_duration = 0
      @user.meetings.where(start_date: date.beginning_of_month..date.end_of_month).each { |meeting| total_duration += meeting.duration.to_i}
      total_duration
    end

    def user_total_all
      total_duration = 0
      @user.meetings.each { |meeting| total_duration += meeting.duration.to_i}
      total_duration
    end

    def user_count(date)
      @user.meetings.where(start_date: date.beginning_of_month..date.end_of_month).count
    end

    def user_count_all
      @user.meetings.count
    end

    def user_percentage(date)
      user_total_minutes = user_total(date) / 60
      ((user_total_minutes / weekday_hour(date).to_f) * 100).round(2)
    end

    def user_meeting_wages(date)
      (@user.wage * (user_percentage(date) / 100)).round(0)
    end

    @total_cost = 0
    @users.each do |user|
      @total_cost += (user_meeting_wages(Date.parse("160")) + user_meeting_wages(Date.parse("140")) + user_meeting_wages(Date.parse("110"))) + 43750 + 35830 + 26480
    end

    @this_cost = 0
    @users.each do |user|
      @this_cost += user_meeting_wages(@date)
    end

    @last_cost = 0
    @users.each do |user|
      @last_cost += user_meeting_wages(@last_date)
    end

    # thismonth user
    @this_user_total = user_total(@date)
    @this_user_count = user_count(@date)
    @this_user_average = @this_user_total / @this_user_count
    @user_percentage = user_percentage(@date)
    @user_meeting_wages = user_meeting_wages(@date)

    # chart for all
    @chart_data = {
      labels: %w[January February March April May June],
      datasets: [
        # {
        # label: 'top created',
        # backgroundColor: 'transparent',
        # borderColor: '#39B54A',
        # data: [top(Date.parse("110"))[1] + 7, top(Date.parse("110"))[1] + 4, top(Date.parse("110"))[1], top(Date.parse("140"))[1], top(Date.parse("140"))[1], top(Date.parse("160"))[1]]},
        {
        label: 'Total number of MTG',
        backgroundColor: 'transparent',
        borderColor: '#3B82F6',
        data: [total_count(Date.parse("110")) - 72, total_count(Date.parse("110")) - 53, total_count(Date.parse("110")) - 24, total_count(Date.parse("110")), total_count(Date.parse("140")), total_count(Date.parse("160"))]
      }, {
        label: 'Total duration(hour)',
        backgroundColor: 'transparent',
        borderColor: '#E24328',
        data: [(total_duration(Date.parse("110")) / 60 ) - 60, (total_duration(Date.parse("110")) / 60 ) - 43, (total_duration(Date.parse("110")) / 60 ) - 22, (total_duration(Date.parse("110")) / 60 ), (total_duration(Date.parse("140")) / 60), (total_duration(Date.parse("160")) / 60)]
      }]
    }

    @chart_options = {
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: true
          }
        }]
      }
    }
    # chart for users
    @chart_data_second = {
      labels: %w[Jan Feb Ma Apr May Jun],
      datasets: [
        # {
      #   label: 'Total duration',
      #   backgroundColor: 'transparent',
      #   borderColor: '#39B54A',
      #   data: [user_total(Date.parse("110")) - 123, user_total(Date.parse("110")) - 79, user_total(Date.parse("110")) - 23, user_total(Date.parse("110")), user_total(Date.parse("140")), user_total(Date.parse("160"))]
      # }, {
      #   label: 'Total number of MTG',
      #   backgroundColor: 'transparent',
      #   borderColor: '#3B82F6',
      #   data: [user_count(Date.parse("110")) - 123, user_count(Date.parse("110")) - 79, user_count(Date.parse("110")) - 23, user_count(Date.parse("110")), user_count(Date.parse("140")), user_count(Date.parse("160"))]
      # },
      {
        label: 'Total cost ¥',
        backgroundColor: 'transparent',
        borderColor: '#E24328',
        data: [user_meeting_wages(Date.parse("110")) - 2302, user_meeting_wages(Date.parse("110")) - 1734, user_meeting_wages(Date.parse("110")) - 336, user_meeting_wages(Date.parse("110")), user_meeting_wages(Date.parse("140")), user_meeting_wages(Date.parse("160"))]
      }]
    }

    @chart_options_second = {
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: true
          }
        }]
      }
    }
  end

  def show
    @meeting = Meeting.find(params[:id])
    @start_time = @meeting.start_date - 9.hours
    @end_time = @meeting.end_date - 9.hours
    @booking = @meeting.bookings
    @attendance = @meeting.bookings.map { |booking| booking.user }
    @organizer = User.find(@meeting.user_id)
    @message = Message.new
    @objectives = @meeting.objectives.strip.gsub('Objectives:', '').split("Agenda:")[0].split("\n")
    @agenda = @meeting.objectives.strip.split("Agenda:")[1].split("\n")
    if @meeting.video && @meeting.video.summary
      @summary = @meeting.video.summary.split('.')
      @actions = @meeting.video.actions.split(/\d+\./)[1..-1]
    end
    authorize @meeting

  end

  def new
    @meeting = Meeting.new
    if params[:description] && params[:usersnames]
      @users_names = params[:usersnames].split(",")
      @users = []
      @users_names.each { |name| @users << User.where(name: name).first }
      @next_available_start_date = User.find_available(@users)
      fetch_optimal_duration
      @location = "Room 1"
      @next_available_end_date = @next_available_start_date + Rational(@duration.to_i, 1440)
      fetch_objectives_and_agenda(@next_available_start_date, @next_available_end_date)
      f = ActionView::Helpers::FormBuilder.new(:meeting, @meeting, self, {})
      respond_to do |format|
        format.html
        format.text { render partial: "meeting_result", locals: {
          duration: @duration,
          reason_duration: @reason_duration,
          objectives_and_agenda_text: @objectives_and_agenda_text,
          next_available_start_date: @next_available_start_date,
          next_available_end_date: @next_available_end_date}, formats:[:html] }
      end
    elsif params[:query] && params[:query] != ""
      @users_filtered = User.where("name ILIKE ?", "%#{params[:query]}%")
      respond_to do |format|
        format.html
        format.text { render partial: "list", locals: { users: @users_filtered }, formats: [:html] }
      end
    else
      @users_filtered = []
    end
    authorize @meeting
  end

  def create
    @users = []
    @meeting = Meeting.new(meeting_params)
    @duration = ((DateTime.parse(params[:end_date]).to_time - DateTime.parse(params[:start_date]).to_time) / 60).to_i

app/views/meetings/_actionmodal.html.erb
<button type="button" class="btn p-0" data-bs-toggle="modal" data-bs-target="#actionModal" data-bs-whatever="@mdo">Actions</button>
<div class="modal fade" id="actionModal" tabindex="-1" aria-labelledby="actionModalLabel" aria-hidden="true">
  <div data-controller="copy">
    <div class="modal-dialog" style="margin-left:100px;">
      <div class="modal-content" style="width: 1300px;">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="actionModalLabel">Actions</h1>
          <% if !@actions.nil? %>
            <button data-action="click->copy#copyToClipboard" class="btn btn-success m-2"><i class="fa-regular fa-clone"></i>
              copy</button>
          <% end %>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <% if @actions.nil?  %>
            <p>No actions</p>
          <% else %>
            <%  @actions.each_with_index do |action, index| %>
              <p data-copy-target="text"><%= index + 1 %>.<%= action %></p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meetings/_avatars.html.erb
<div >
  <% if users.length >= 1 %>
    <% users.each do |user|%>
      <span data-controller="popover" data-popover-url-value="<%= user_card_path(user) %>">
        <%= link_to meetings_path(user_id: user.id, query: params[:query]), class:"text-decoration-none avatar-search-icon", data: { action: "mouseenter->popover#show mouseleave->popover#hide" } do %>
          <%= image_tag user.photo.key ? cl_image_path(user.photo.key) :  "gorilla.jpg", class: "avatar m-1"%>
        <% end %>
      </span>
    <% end %>
  <% end %>
</div>

app/views/meetings/_avatarsfa.html.erb
 <% if users.length >= 1 %>
  <% users.each do |user|%>
    <%= link_to meetings_analytics_path(user_id: user.id, query: params[:query], tab:"conversations-tab"), class:"text-decoration-none" do %>
      <%= image_tag user.photo.key ? cl_image_path(user.photo.key) :  "gorilla.jpg", class: "avatar m-1"%>
    <% end %>
  <% end %>
<% end %>

app/views/meetings/_create_form.html.erb
<div class="container m-auto" data-controller="search-users">
  <h1 class="input-button">New meeting</h1>
  <form action="/meetings/new" method="get" data-search-users-target="form">
    <input
      type="text"
      name="query"
      data-search-users-target="input"
      data-action="keyup->search-users#search"
      value="<%= params[:query] %>"
      >
    </form>
    <div id="form-container" data-controller="form-steps">
      <%= simple_form_for @meeting, data: { controller: 'flatpickr' } do |f| %>
        <div class="input-button" data-form-steps-target="step">
          <div data-search-users-target="users">
            <% if @users_filtered.present? && @users_filtered.length.positive? %>
              <%= render 'list' %>
            <% else %>
              <p>No users found.</p>
            <% end %>
          </div>
          <div data-search-users-target="usersClicked" class="hidden"></div>
          <button type="button" data-action="click->form-steps#nextStep" class="button-general ml-3" role="button">Next</button>
        </div>
        <div data-form-steps-target="step" class="hidden">
          <%= f.input :description %>
          <button type="button" data-action="click->form-steps#nextStep" class="button-general" role="button">Next</button>
        </div>
        <div data-form-steps-target="step" class="hidden">
          <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
          <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endTime" }, id: 'end_time' } %>
          <button type="button" data-action="click->form-steps#nextStep" class="button-general" role="button">Next</button>
        </div>
        <div data-form-steps-target="step" class="hidden">
          <%= f.input :duration %>
          <button type="button" data-action="click->form-steps#nextStep" class="button-general" role="button">Next</button>
        </div>
        <div data-form-steps-target="step" class="hidden">
          <%= f.input :location %>
          <%= f.submit class:"button-general", role:"button"%>
        </div>
      <% end %>
    </div>
  </div>

app/views/meetings/_list.html.erb
 <% if users.length >= 1 %>
  <% users.each_with_index do |user, index| %>
    <style>
      .check {
          display: none;
      }
      .check:checked+label{
        box-shadow: 0px 0px 2px black;
        background: lavender;
        border-radius: 4px;
        padding: 2px;
          }
      .check:checked+label img{
        border:2px solid #000064;
        transition:0.3s ease;
      }
    </style>
    <input
            data-form-steps-target="checkbox"
            id= "name<%=index%>"
            type="checkbox"
            name="users[]"
            value= "<%= user.name%>"
            class="check">
      <label for="name<%=index%>">
        <%= image_tag user.photo.key ? cl_image_path(user.photo.key) :  "gorilla.jpg", class: "avatar"%>
        <%= user.name %>
      </label>
    <% end %>
  <% end %>

app/views/meetings/_meeting_result.html.erb
<div class="d-flex" class="input-button animate__animated animate__fadeInRight" style="margin-left: 64px; width:100%;">
  <img src="<%=asset_path('logo.png')%>" style="height: 50px;" alt="">
  <!-- Button trigger modal -->
  <div>
    <div data-controller="popover">
      <p data-action="mouseenter->popover#show mouseleave->popover#hide" >Optimal Duration: <%= duration %></p>
      <template data-popover-target="content">
        <div class= "reason-duration" data-popover-target="card">
          <p>Reason: <%= reason_duration %> </p>
        </div>
      </template>
    </div>
    <p>Available Room: <%= @location %></p>
    <div class="d-flex">
      <p>Next Available meeting:</p>
      <input class = "form-output" type="datetime-local" name="start_date" id="meeting_start_date" style=" width: 345px; margin-right: 25px; margin-left: 25px; background: lavender" data-flatpickr-target="startTime" data-form-steps-target="startTime" value="<%= next_available_start_date.strftime('%Y-%m-%dT%H:%M') %>">
      <input class = "form-output" type="datetime-local" name="end_date" id="meeting_end_date" style="width: 345px; background: lavender" data-flatpickr-target="endTime" data-form-steps-target="endTime" id="end_time" value="<%= next_available_end_date.strftime('%Y-%m-%dT%H:%M') %>">
    </div>
    <textarea style="width: 930px;"autocomplete="off" type="" name="meeting[objectives]" id="meeting_objectives"><%= sanitize objectives_and_agenda_text %></textarea>
    <div style="margin-top: 32px; border: none;">
      <input  type="submit" name="commit" value="Book the Meeting" class="button-general" role="button" data-disable-with="Create Meeting">
    </div>
  </div>
</div>

app/views/meetings/_next_available_start_date.erb
<%= sanitize @next_available_time %>

app/views/meetings/_objectives_and_agenda.html.erb
<div class="d-flex" style="margin-top: 20px; margin-left: 64px;">
  <img class="logoimg" src="<%=asset_path('logo.png')%>" style="height: 50px;" alt="" class="animate__animated animate__fadeInRight">
  <p> <%= sanitize result %> </p>
  <input class="form-control hidden" autocomplete="off" type="" name="meeting[objectives]" id="meeting_objectives" value="<%= sanitize result %>">
</div>

app/views/meetings/index.html.erb
<div class="index-container" data-controller="calendar">
  <div class="left" data-controller="search-users">
    <div class="refresh">
    </div>
    <div class="avatar-search">
      <i class="fa-solid fa-user-group fa-2xl" style="color: #000064
      "></i>
      <form action="/meetings" method="get" data-search-users-target="form">
        <input
          class="index-input"
          style="background: lavender; border-radius:5px;"
          type="text"
          name="query"
          data-search-users-target="input"
          data-action="keyup->search-users#search"
          value="<%= params[:query] %>"
          >
        </form>
      </div>
      <div id="form-container" class="avataravatar">
        <div>
          <div data-search-users-target="users">
            <% if @users_filtered.present? && @users_filtered.length.positive? %>
              <%= render 'avatars', users: @users_filtered %>
            <% end %>
          </div>
        </div>
        <div data-search-users-target="usersClicked" class="hidden"></div>
      </div>
      <%= link_to meetings_analytics_path,  class: "text-decoration-none" do%>
        <div class="btn btn-analytics" >
          <i class="fa-solid fa-chart-line fa-2xl" style="color: #000064
          "></i>
          <p>Analytics</p>
        </div>
      <% end %>
      <div class="btn btn-organizing" data-action="click->calendar#toggle">
        <i class="fa-solid fa-clipboard fa-2xl" style="color: #000064;"></i>
        <p>Created Meetings</p>
      </div>
      <div class="created-meeting" data-calendar-target="meetings">
        <p class="meeting-title-a">Past Meetings</p>
        <% if @past_meetings.any?  %>
          <% @past_meetings.each do |meeting| %>
            <div class="meeting-title">
              <i class="fa-solid fa-circle"></i>
              <p class="btn" data-bs-toggle="modal" data-bs-target="#exampleModal<%=meeting.id%>" ><%= meeting.title.capitalize %></p>
            </div>
            <div class="modal fade" id="exampleModal<%=meeting.id%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><%= meeting.title.capitalize %></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <div class="meeting-start-time">
                      <i class="fa-solid fa-clock"></i>
                      <p><%= meeting.start_date.strftime("%A, %d %b %Y %l:%M %p") %></p>
                    </div>
                    <div class="meeting-duration">
                      <i class="fa-solid fa-clock-rotate-left"></i>
                      <p> <%= meeting.duration %> minutes</p>
                    </div>
                    <div class="meeting-attendees">
                      <i class="fa-solid fa-people-group"></i>
                      <p>Attendees</p>
                    </div>
                    <% meeting.bookings.sort_by(&:status).each do |booking|%>
                      <% case booking.status %>
                      <%   when "accepted"%>
                      <%= image_tag booking.user.photo.key ? cl_image_path(booking.user.photo.key) :  "gorilla.jpg", class: "avatar m-1 border border-3 border-success"%>
                      <%   when "pending"%>
                      <%= image_tag booking.user.photo.key ? cl_image_path(booking.user.photo.key) :  "gorilla.jpg", class: "avatar m-1 border border-3 border-info"%>
                      <%   when "rejected"%>
                      <%= image_tag booking.user.photo.key ? cl_image_path(booking.user.photo.key) :  "gorilla.jpg", class: "avatar m-1 border border-3 border-danger"%>
                    <% else %>
                    <% end %>
                  <% end %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p class="text-muted" style="font-size: 12px">There are no past meetings</p>
      <% end %>
      <p class="meeting-title-a mt-3">Upcoming Meetings</p>
      <% if @upcoming_meetings.any?  %>
        <% @upcoming_meetings.each do |meeting| %>
          <div class="meeting-title">
            <i class="fa-solid fa-circle"></i>
            <p class="btn" data-bs-toggle="modal" data-bs-target="#exampleModal<%=meeting.id%>"><%= meeting.title.capitalize %></p>
          </div>
          <div class="modal fade" id="exampleModal<%=meeting.id%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel"><%= meeting.title.capitalize %></h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <div class="meeting-start-time">
                    <i class="fa-solid fa-clock"></i>
                    <p><%= meeting.start_date.strftime("%A, %d %b %Y %l:%M %p") %></p>
                  </div>
                  <div class="meeting-duration">
                    <i class="fa-solid fa-clock-rotate-left"></i>
                    <p> <%= meeting.duration %> minutes</p>
                  </div>
                  <div class="meeting-attendees">
                    <i class="fa-solid fa-people-group"></i>
                    <p>Attendees</p>
                  </div>
                  <% meeting.bookings.sort_by(&:status).each do |booking|%>
                    <% case booking.status %>
                    <%   when "accepted"%>
                    <%= image_tag booking.user.photo.key ? cl_image_path(booking.user.photo.key) :  "gorilla.jpg", class: "avatar m-1 border border-3 border-success"%>
                    <%   when "pending"%>
                    <%= image_tag booking.user.photo.key ? cl_image_path(booking.user.photo.key) :  "gorilla.jpg", class: "avatar m-1 border border-3 border-info"%>
                    <%   when "rejected"%>
                    <%= image_tag booking.user.photo.key ? cl_image_path(booking.user.photo.key) :  "gorilla.jpg", class: "avatar m-1 border border-3 border-danger"%>
                  <% else %>
                  <% end %>
                <% end %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-muted" style="font-size: 12px">There are no upcoming meetings</p>
    <% end %>
  </div>
</div>
<div class="right">
  <div class="container-c"  >
    <div class="calendar-buttons">
      <div class="switching">
        <div class="btn btn-flat" data-action="click->calendar#monthly">
          Month
        </div>
        <div class="btn btn-flat" data-action="click->calendar#weekly">
          Week
        </div>
      </div>
      <div class="btn-organizing-new switching" data-bs-toggle="modal" data-bs-target="#newMeeting" >
        <%# <%= render 'modal', meeting: @meeting %>
        <%= link_to new_meeting_path do%>
          <i class="fa-regular fa-calendar-plus fa-2xl" style="color: #000064;"></i>
          New Meeting
        <% end %>
      </div>
    </div>
    <div class="monthly-calendar" data-calendar-target="month">
      <%= month_calendar(events: @meetings, attribute: :start_date) do |date, meetings| %>
        <div class="dayday">
          <%= date.mday  %>
        </div>
        <% meetings.each do |meeting| %>
          <%= link_to meeting_path(meeting), class:"text-decoration-none" do %>
            <% if  meeting.user == current_user%>
              <div class="calendar-card" style="background-color: #164BB5">
                <div class="calendar-title" style="color: white">
                  <%= meeting.title.capitalize%>
                </div>
              </div>
            <% else %>
              <div class="calendar-card">
                <div class="calendar-title">
                  <%= meeting.title.capitalize %>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="weekly-calendar hidden" data-calendar-target="week">
      <%= week_calendar(events: @meetings, attribute: :start_date) do |date, meetings| %>
        <div class="dayday">
          <%= date.mday  %>
        </div>
        <% meetings.each do |meeting| %>
          <%= link_to meeting_path(meeting), class:"text-decoration-none" do %>
            <% if  meeting.user == current_user%>
              <div class="calendar-card-week" style="background-color: #164BB5">
                <div class="calendar-time">
                  <%= meeting.start_date.strftime("%k:%M ~") %>
                </div>
                <div class="calendar-title">
                  <%= meeting.title.capitalize %>
                </div>
              </div>
            <% else %>
              <div class="calendar-card-week">
                <div class="calendar-time">
                  <%= meeting.start_date.strftime("%k:%M ~") %>
                </div>
                <div class="calendar-title">
                  <%= meeting.title.capitalize %>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
</div>
</div>